import type { PipelineStage } from './types';

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'input',
    label: '16 LR Observations',
    shortLabel: '16 LR',
    status: 'completed',
    whatEnters: '16 multi-temporal low-resolution Sentinel-2 L2A acquisitions of the same geographic tile, each with 12 spectral bands + cloud/validity masks.',
    whatHappens: 'Raw observations are loaded with their per-pixel quality layers (cloud mask, cloud probability, data mask) and metadata (acquisition date, sun/view angles).',
    whatComesOut: '16 candidate images with associated quality metadata ready for assessment.',
  },
  {
    id: 'quality-filter',
    label: 'Quality Filter',
    shortLabel: 'Filter',
    status: 'completed',
    whatEnters: '16 candidates with quality metrics: valid_pixel_pct, cloud_mask_pct, cloud_probability_pct.',
    whatHappens: 'Apply threshold filters: valid_pixel_pct ≥ 90%, cloud_mask_pct ≤ 20%, cloud_probability_pct ≤ 50% (missing allowed). Candidates failing any threshold are rejected.',
    whatComesOut: 'N usable candidates (varies per tile; e.g. 15 of 16 for Amnesty POI, 3 of 16 for ASMSpotter).',
  },
  {
    id: 'ranking',
    label: 'Quality-Aware Ranking',
    shortLabel: 'Rank',
    status: 'completed',
    whatEnters: 'N usable candidates with temporal distance, cloud probability, cloud mask percentage, valid pixel percentage.',
    whatHappens: 'Compute ranking_score = 0.60 × temporal_quality + 0.30 × cloud_quality + 0.10 × validity_quality, where temporal_quality = exp(-|Δdays|/90).',
    whatComesOut: 'Candidates sorted by ranking_score, each assigned a rank from 1 to N.',
  },
  {
    id: 'topk',
    label: 'Top-K Selection',
    shortLabel: 'Top-K',
    status: 'completed',
    whatEnters: 'N ranked candidates and a user-specified K (default K=4).',
    whatHappens: 'Select the top K candidates by ranking_score. If fewer than K usable candidates exist, select all available. K=1 → single-image SR, K>1 → multi-image SR.',
    whatComesOut: 'K selected observations — the best available inputs for super-resolution.',
  },
  {
    id: 'geo-alignment',
    label: 'Geographic Alignment',
    shortLabel: 'Geo Align',
    status: 'in-progress',
    whatEnters: 'K selected LR observations + 1 HR reference, each with known geographic bounds and CRS.',
    whatHappens: 'Coarse spatial registration using affine transforms derived from geospatial metadata. Corrects for sub-pixel shifts between acquisitions taken at different times.',
    whatComesOut: 'K LR observations co-registered to the HR reference grid at pixel level.',
  },
  {
    id: 'encoder',
    label: 'Feature Encoder',
    shortLabel: 'Encode',
    status: 'planned',
    whatEnters: 'K co-registered LR observation tensors.',
    whatHappens: 'A shared CNN encoder extracts deep feature representations from each observation independently, capturing spatial patterns, edges, and texture information.',
    whatComesOut: 'K feature maps per observation — rich learned representations ready for alignment.',
  },
  {
    id: 'fine-alignment',
    label: 'Learned Feature Alignment',
    shortLabel: 'Fine Align',
    status: 'planned',
    whatEnters: 'K sets of deep feature maps, potentially with sub-pixel misalignments.',
    whatHappens: 'A learned alignment module (e.g. deformable convolutions or optical flow estimation) computes per-pixel offsets to precisely align features across observations.',
    whatComesOut: 'K aligned feature maps with sub-pixel precision — finer than geographic registration alone.',
  },
  {
    id: 'fusion',
    label: 'Attention-Based Fusion',
    shortLabel: 'Fuse',
    status: 'planned',
    whatEnters: 'K aligned feature maps, each representing a different temporal observation.',
    whatHappens: 'A temporal attention mechanism learns per-pixel weights for each observation: how much to trust each image at each spatial location. Higher-quality observations receive higher attention weights.',
    whatComesOut: 'A single fused feature map that intelligently combines the best information from all K observations.',
  },
  {
    id: 'reconstruction',
    label: 'HR Reconstruction',
    shortLabel: 'Reconstruct',
    status: 'planned',
    whatEnters: 'Fused feature map at LR resolution.',
    whatHappens: 'A decoder network with learned upsampling (e.g. sub-pixel convolution / PixelShuffle) reconstructs a high-resolution output from the fused features.',
    whatComesOut: 'Predicted HR image at the target resolution.',
  },
  {
    id: 'evaluation',
    label: 'HR Output',
    shortLabel: 'Output',
    status: 'planned',
    whatEnters: 'Predicted HR image + real HR reference.',
    whatHappens: 'Compute quality metrics: PSNR (peak signal-to-noise), SSIM (structural similarity), SAM (spectral angle mapper). Compare against baselines (bicubic, SISR, unranked MISR).',
    whatComesOut: 'Quantitative evaluation demonstrating the benefit of quality-aware multi-image fusion over alternatives.',
  },
];

export const ROADMAP_PHASES = [
  {
    name: 'Data Foundation',
    status: 'completed' as const,
    items: [
      'Dataset exploration',
      'HR/LR scene organization',
      'LR candidate extraction',
    ],
  },
  {
    name: 'Quality-Aware Selection',
    status: 'completed' as const,
    items: [
      'Quality feature extraction',
      'Temporal distance calculation',
      'Cloud probability analysis',
      'Cloud-mask analysis',
      'Valid-pixel analysis',
      'Quality filtering',
      'Quality-aware candidate ranking',
      'Top-K candidate extraction',
      'Candidate manifest generation',
      'Multi-candidate LR loading/inspection',
    ],
  },
  {
    name: 'Spatial Alignment',
    status: 'in-progress' as const,
    items: [
      'Geographic alignment',
      'MISR dataset construction',
    ],
  },
  {
    name: 'MISR Core',
    status: 'planned' as const,
    items: [
      'Feature extraction',
      'Learned feature alignment',
      'Multi-image fusion',
      'HR reconstruction',
    ],
  },
  {
    name: 'Training & Evaluation',
    status: 'planned' as const,
    items: [
      'Full MISR model training',
      'Ablation studies (K=1/2/4/8/16)',
      'Baseline comparison',
      'PSNR/SSIM/SAM evaluation',
    ],
  },
  {
    name: 'Final System',
    status: 'planned' as const,
    items: [
      'Robust variable-K handling',
      'Final deployment',
    ],
  },
];
